### ISSUE TITLE
Image component renders as div.

### ISSUE THREAD

**Issue by jckw** [rebassjs/rebass#499]
Using: 

```
        "rebass": "^3.0.0-4",
        "styled-components": "^3.4.5",
```

When an `Image` is rendered, it appears as a `div` (and therefore the `src` prop is passed as a DOM attribute).

**Comment by TrySound** [comment]
Rebass prerelease requires styled-copmonents v4 with `as` prop support

**Comment by jckw** [comment]
Just tried using styled-components 4.0.0-beta.1 and have the same issue. The `as` prop gets made into an attribute as well. 

Example of the rendered div: 

```
<div class="sc-bZQynM ..." src="..." height="24px" as="img"></div>
```

**Comment by TrySound** [comment]
Check your node_modules. Make sure it's v4. `as` prop was added here
https://github.com/styled-components/styled-components/releases/tag/v4.0.0-beta.0
Probably the bug in styled-components.

**Comment by ckeeney** [comment]
I had this same problem a couple days ago.  I think before this issue is closed, the minimum version of styled components should be documented somewhere.

**Comment by gregoralbrecht** [comment]
I'm having the same issue with the `Button` and `Text` components using:
```
"rebass": "^3.0.0-4",
"styled-components": "^4.0.0-beta.3"
```

I'm using "styled-components based extension" as mentioned in the docs like this:
```
import styled from 'styled-components'
import { Button } from 'rebass'

export default styled(Button)`background: pink`
```
Can anyone tell me what I'm missing?

**Comment by jxnblk** [comment]
@gregoralbrecht be sure to install the latest versions of each beta – I know some things have been fixed since those releases

**Comment by gregoralbrecht** [comment]
@jxnblk I did, I'm using these versions and still no luck, my `Button` renders as `div`:
```
"rebass": "^3.0.0-8",
"styled-components": "^4.0.0-beta.7"
```

**Comment by jxnblk** [comment]
@gregoralbrecht also, if you’re only adjust background color, you should use the `bg` prop since that’s baked in – using the React-based extending would make more sense in that case, see https://rebassjs.org/extending

**Comment by jxnblk** [comment]
@gregoralbrecht Ah, that's interesting – might be worth opening an issue on styled-components to ask about that behavior

**Comment by nicholaai** [comment]
@gregoralbrecht, you can try using `defaultProps`

```js
import styled from 'styled-components'
import { Button } from 'rebass'

const PinkButton styled(Button)``;

PinkButton.defaultProps = {
  bg: 'pink'
};

export default PinkButton
```
